# Generated by Django 3.2.3 on 2021-06-08 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='polls.Course'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 9, 5, 21, 53, 101615)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BigIntegerField(choices=[(0, 'Cancelled'), (1, 'Confirmed'), (2, 'On Hold')], default=1),
        ),
    ]
