# Generated by Django 3.2.3 on 2021-06-08 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210609_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 9, 5, 31, 6, 114707)),
        ),
    ]
