# Generated by Django 3.2.5 on 2021-07-19 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210720_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 20, 1, 37, 37, 188092)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.EmailField(max_length=254)),
                ('rating', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.datetime(2021, 7, 19, 17, 37, 37, 192096, tzinfo=utc))),
                ('datetime', models.DateTimeField(default=datetime.datetime(2021, 7, 20, 1, 37, 37, 192096))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.course')),
            ],
        ),
    ]
