# Generated by Django 3.2.5 on 2021-08-05 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210805_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to=polls.models.Student.user_directory_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 6, 2, 2, 30, 215678)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 5, 18, 2, 30, 216671, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 6, 2, 2, 30, 216671)),
        ),
    ]
